config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :campaigns
  resources :candidates

  root 'campaigns#index'
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :candidates, through: :elections
  has_many :elections, dependent: :destroy
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :campaigns, through: :elections
  has_many :elections, dependent: :destroy


  def votes_counted_in_campaign(campaign)
    self.elections.where(campaign: campaign).first.votes.where(validity: 'during').count
  end
  def votes_not_counted_in_campaign(campaign)
    votes = self.elections.where(campaign: campaign).first.votes
    votes.count - votes.where(validity: 'during').count
  end
end

app/models/election.rb
class Election < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :candidate
  validates :candidate_id, uniqueness: { scope: [:campaign_id] }
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :campaign
  belongs_to :election

  def self.parse_vote_string(str)
    #v = str.force_encoding("ISO-8859-1").encode("utf-8", replace: nil).split("\s")
    begin
      v = str.split("\s")
    rescue => e
      puts "Something went wrong, string ignored. Error message: #{e.message}"
      return false
    end
    if v.count == 9
      campaign = v[2].split(':')
      validity = v[3].split(':')
      choice = v[4].split(':')
      conn = v[5].split(':')
      msisdn = v[6].split(':')
      guid = v[7].split(':')
      shortcode = v[8].split(':')
    else
      return false
    end
    if v[0] == "VOTE" && v[1].is_numeric? && campaign[0] == "Campaign" && !campaign[1].blank? && validity[0] == "Validity" && %w(pre during post).include?(validity[1]) && choice[0] == "Choice" && conn[0] == "CONN" && msisdn[0] == "MSISDN" && msisdn[1].is_numeric? && guid[0] == "GUID" && shortcode[0] == "Shortcode" && shortcode[1].is_numeric?
      return {vote_time: v[1].to_i, validity: validity[1], campaign: campaign[1], candidate: choice[1]}
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'mgage'
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @candidates = @campaign.candidates
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:name, :has_many)
    end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.order(:vote_time).page params[:page]
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:vote_time, :validity, :conn, :msisdn, :guid, :shortcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/campaigns/_form.html.erb
<%= form_for @campaign, :html => { :class => "form-horizontal campaign" } do |f| %>

    <% if @campaign.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @campaign.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@campaign[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            campaigns_path, :class => 'btn btn-default' %>

<% end %>

app/views/campaigns/edit.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaigns/index.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= link_to campaign.id, campaign_path(campaign) %></td>
        <td><%= link_to campaign.name, campaign_path(campaign)  %></td>
        <td><%=l campaign.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_campaign_path(campaign), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      campaign_path(campaign),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_campaign_path,
            :class => 'btn btn-primary' %>

app/views/campaigns/new.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaigns/show.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @campaign.name %></dd>
</dl>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= Candidate.human_attribute_name(:id) %></th>
    <th><%= Candidate.human_attribute_name(:name) %></th>
    <th><%= t(:scores) %></th>
    <th><%= t(:number_of_not_counted_messages) %></th>
  </tr>
  </thead>
  <tbody>
  <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to candidate.id, candidate_path(candidate) %></td>
        <td><%= candidate.name %></td>
        <td><%= candidate.votes_counted_in_campaign @campaign %></td>
        <td><%= candidate.votes_not_counted_in_campaign @campaign %></td>
      </tr>
  <% end %>
  </tbody>
</table>



<%= link_to t('.back', :default => t("helpers.links.back")),
              campaigns_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_campaign_path(@campaign), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              campaign_path(@campaign),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/candidates/_form.html.erb
<%= form_for @candidate, :html => { :class => "form-horizontal candidate" } do |f| %>

    <% if @candidate.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @candidate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@candidate[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            candidates_path, :class => 'btn btn-default' %>

<% end %>

app/views/candidates/edit.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/candidates/index.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to candidate.id, candidate_path(candidate) %></td>
        <td><%= link_to candidate.name, candidate_path(candidate) %></td>
        <td><%=l candidate.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_candidate_path(candidate), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      candidate_path(candidate),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_candidate_path,
            :class => 'btn btn-primary' %>

app/views/candidates/new.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/candidates/show.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @candidate.name %></dd>
</dl>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= Campaign.human_attribute_name(:id) %></th>
    <th><%= Campaign.human_attribute_name(:name) %></th>
  </tr>
  </thead>
  <tbody>
  <% @candidate.campaigns.each do |campaign| %>
      <tr>
        <td><%= link_to campaign.id, campaign_path(campaign) %></td>
        <td><%= link_to campaign.name, campaign_path(campaign)  %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<%= link_to t('.back', :default => t("helpers.links.back")),
              candidates_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_candidate_path(@candidate), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              candidate_path(@candidate),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mgage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/mgage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mgage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--<a class="navbar-brand" href="#">Mgage</a>-->
        <%= link_to "Campaigns", root_path, class: "navbar-brand"  %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Candidates", candidates_path  %></li>
            <li><%= link_to "Votes", votes_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <br/>
      <footer>
        <p>&copy; mGage 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/votes/_form.html.erb
<%= form_for @vote, :html => { :class => "form-horizontal vote" } do |f| %>

    <% if @vote.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @vote.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :vote_time, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vote_time, :class => 'form-control' %>
    </div>
    <%= error_span(@vote[:vote_time]) %>
  </div>
  <div class="control-group">
    <%= f.label :validity, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :validity, :class => 'form-control' %>
    </div>
    <%= error_span(@vote[:validity]) %>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            votes_path, :class => 'btn btn-default' %>

<% end %>

app/views/votes/edit.html.erb
<%- model_class = Vote -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/votes/index.html.erb
<%- model_class = Vote -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div style="text-align: center">
  <%= paginate @votes %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:vote_time) %></th>
      <th><%= model_class.human_attribute_name(:validity) %></th>
      <th><%= t(:campaign) %></th>
      <th><%= t(:candidate) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= link_to vote.id, vote_path(vote) %></td>
        <td><%= vote.vote_time %></td>
        <td><%= vote.validity %></td>
        <td><%= vote.election.campaign.name %></td>
        <td><%= vote.election.candidate.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vote_path(vote), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vote_path(vote),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vote_path,
            :class => 'btn btn-primary' %>

app/views/votes/new.html.erb
<%- model_class = Vote -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/votes/show.html.erb
<%- model_class = Vote -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:vote_time) %>:</strong></dt>
  <dd><%= @vote.vote_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:validity) %>:</strong></dt>
  <dd><%= @vote.validity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:candidate_id) %>:</strong></dt>
  <dd><%= @vote.candidate_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:campaign_id) %>:</strong></dt>
  <dd><%= @vote.campaign_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              votes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vote_path(@vote), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vote_path(@vote),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>